# Generated by Django 4.1.7 on 2023-03-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_category_id_alter_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color_product',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
